### PR TITLE
Fix for 0.6

### PR DESCRIPTION
**Pull request by sambitdash**
- Removed support for 0.4
- Fixed the array declaration warnings
- Fixed test cases

### CODE REVIEW

**Comment by sambitdash** [comment]
rebuilding hence closing and opening. the codecov errors do not look quite ok.

**Comment by oxinabox** [comment]
@weijianzhang  can this be looked at?

**Comment by weijianzhg** [comment]
@oxinabox I think we could merge this pull request. Looks good to me.

Had a check of https://travis-ci.org/JuliaText/Word2Vec.jl , this pull request has passed the test. I don't understand why the Status Image shows build error.

**Comment by oxinabox** [comment]
yeah, that is a weird one.

**Comment by weijianzhg** [comment]
If there is no further comment, I will merge this push and deal with the travis Status Image thing later.

**Pull request merged**
